[package]
name = "ek-tm4c1294xl-demo"
version = "0.1.0"
authors = ["whitequark <whitequark@whitequark.org>"]

[dependencies]
cortex-m = "0.2.4"
cortex-m-rt = { version = "0.2.0", features = ["linker-script"], default-features = false }
tm4c129x = "0.3.0"

[profile.release]
lto = true
debug = true

[replace]
"cortex-m:0.2.4" = { git = "https://github.com/whitequark/cortex-m", rev = "impl-syst" }
